# Generated by Django 6.0 on 2025-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_avatar_food_image_ordereditems_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='orders/'),
        ),
    ]
