# Generated by Django 6.0 on 2025-12-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_avatar_alter_food_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='image',
        ),
    ]
