# Generated by Django 6.0 on 2025-12-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ordereditems_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
    ]
